language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - nightly
script:
  - python --version
  - flake8 tkinder/ tests/

  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
  - xvfb-run python -m pytest
